### ISSUE TITLE
Build error when upgrading teamengine-spi from 5.2.2 to 5.7

### ISSUE THREAD

**Issue by jiann** [opengeospatial/ets-trainingdmlai10-part2#25]
Version 5.5.2 showed error messages, though the test suite ran successfully
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.NullPointerException
	at com.occamlab.te.vocabulary.Config.getElementsByTagName(Config.java:189)
	at com.occamlab.te.vocabulary.Config.<init>(Config.java:84)
	at com.occamlab.te.spi.executors.testng.EarlReporter.<init>(EarlReporter.java:95)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:165)
	at org.opengis.cite.trainingdmlai10part2.TestNGController.doTestRun(TestNGController.java:138)
	at org.opengis.cite.trainingdmlai10part2.TestNGController.main(TestNGController.java:78)
```

Version 5.6.1, 5.7 showed error messages and the build failed
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider com.occamlab.te.spi.executors.testng.EarlReporter could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at com.occamlab.te.spi.executors.testng.TestNGExecutor.execute(TestNGExecutor.java:170)
	at org.opengis.cite.trainingdmlai10part2.TestNGController.doTestRun(TestNGController.java:138)
	at org.opengis.cite.trainingdmlai10part2.TestNGController.main(TestNGController.java:78)
Caused by: java.lang.NullPointerException
	at com.occamlab.te.config.Config.getOrganizations(Config.java:300)
	at com.occamlab.te.config.Config.<init>(Config.java:90)
	at com.occamlab.te.spi.executors.testng.EarlReporter.<init>(EarlReporter.java:97)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 8 more
Disconnected from the target VM, address: '127.0.0.1:58950', transport: 'socket'

Process finished with exit code 1
```
Both the Maven build and Docker build succeed using the following commands:
`mvn clean install`
`mvn clean install -Dsource=8 docker:run -Pdocker `

**Comment by dstenger** [comment]
@jiann Can you please describe how you executed the tests with your IDE leading to the reported error (e.g. you started class TestNGController with following arguments)?

**Comment by jiann** [comment]
The build error occurred when I was using the IDE (IntelliJ IDEA) to run the TestNG controller.
<img width="1344" alt="image" src="https://github.com/user-attachments/assets/becb5246-3385-453d-a68a-247c3680116c">

The content of test-run-props.xml was
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties version="1.0">
    <comment>Sample test run arguments</comment>
    <entry key="iut">
        file:///Users/jiann/Projects/JavaRepo/ets-trainingdmlai10-part2/src/test/resources/test1/WHU-RS19.json
    </entry>
    <entry key="ics">class-A,class-B</entry>
</properties>

```

**Comment by dstenger** [comment]
Problem is most likely related to this PR: https://github.com/opengeospatial/teamengine/pull/562
Following issue shall also be considered: https://github.com/opengeospatial/ets-wfs20/issues/261

**Comment by dstenger** [comment]
@jiann Unfortunately, we cannot reproduce your problem.
One possible problem might be that you have a config.xml located in your home folder which is used instead the one located inside the project.
Can you please check that? If a config.xml exists in your home folder, please rename it and check if the problem still occurs.

**Comment by jiann** [comment]
There is a config.xml file that existed in my home folder, which was located in home/teamengine/config.xml. 
This issue was solved by removing the teamengine folder.
